from bot.services.errors import (
    MatchingQueueError,
    PlayerAlreadyRegisteredError,
    PlayerNotRegisteredError,
    QueueAlreadyJoinedError,
    QueueNotJoinedError,
    RegistrationError,
)
from bot.services.matching_queue import (
    DEFAULT_CLEANUP_BATCH_SIZE,
    MATCH_PLAYER_COUNT,
    MATCH_QUEUE_TTL,
    PRESENCE_REMINDER_LEAD_TIME,
    CreatedMatchResult,
    ExpireQueueEntryResult,
    ExpireTask,
    JoinQueueResult,
    LeaveQueueResult,
    MatchingQueueService,
    MatchingQueueTaskScheduler,
    NoopMatchingQueueTaskScheduler,
    PresenceReminderResult,
    PresenceReminderTask,
    PresentQueueResult,
    StartupSyncResult,
)
from bot.services.registration import register_player

__all__ = [
    "CreatedMatchResult",
    "DEFAULT_CLEANUP_BATCH_SIZE",
    "ExpireQueueEntryResult",
    "ExpireTask",
    "JoinQueueResult",
    "LeaveQueueResult",
    "MATCH_PLAYER_COUNT",
    "MATCH_QUEUE_TTL",
    "MatchingQueueError",
    "MatchingQueueService",
    "MatchingQueueTaskScheduler",
    "NoopMatchingQueueTaskScheduler",
    "PlayerAlreadyRegisteredError",
    "PlayerNotRegisteredError",
    "PRESENCE_REMINDER_LEAD_TIME",
    "PresenceReminderResult",
    "PresenceReminderTask",
    "PresentQueueResult",
    "QueueAlreadyJoinedError",
    "QueueNotJoinedError",
    "RegistrationError",
    "register_player",
    "StartupSyncResult",
]
