"""add queue class id to match queue entries

Revision ID: 0360ead067b8
Revises: 7015567383d7
Create Date: 2026-03-21 00:27:46.976617
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '0360ead067b8'
down_revision: str | None = '7015567383d7'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_queue_entries', sa.Column('queue_class_id', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_match_queue_entries_queue_class_id'), 'match_queue_entries', ['queue_class_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_queue_entries_queue_class_id'), table_name='match_queue_entries')
    op.drop_column('match_queue_entries', 'queue_class_id')
    # ### end Alembic commands ###
