"""add presence thread channel id to match queue entries

Revision ID: 05d7cc39fdf0
Revises: 8b5f30ff8718
Create Date: 2026-03-28 23:34:54.226862
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '05d7cc39fdf0'
down_revision: str | None = '8b5f30ff8718'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_queue_entries', sa.Column('presence_thread_channel_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_queue_entries', 'presence_thread_channel_id')
    # ### end Alembic commands ###
