"""create match queue entries table

Revision ID: 070d1ff03326
Revises: 1bf8e60c0cc3
Create Date: 2026-03-15 13:36:40.348802
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '070d1ff03326'
down_revision: str | None = '1bf8e60c0cc3'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_queue_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'left', 'expired', 'matched', name='match_queue_entry_status', native_enum=False, create_constraint=True), server_default=sa.text("'waiting'"), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_present_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('last_reminded_revision', sa.Integer(), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removal_reason', sa.Enum('user_leave', 'timeout', name='match_queue_removal_reason', native_enum=False, create_constraint=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_queue_entries_player_id'), 'match_queue_entries', ['player_id'], unique=False)
    op.create_index('uq_match_queue_entries_waiting_player_id', 'match_queue_entries', ['player_id'], unique=True, postgresql_where=sa.text("status = 'waiting'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_match_queue_entries_waiting_player_id', table_name='match_queue_entries', postgresql_where=sa.text("status = 'waiting'"))
    op.drop_index(op.f('ix_match_queue_entries_player_id'), table_name='match_queue_entries')
    op.drop_table('match_queue_entries')
    # ### end Alembic commands ###
