"""add info thread binding

Revision ID: 16d5f8ac96ff
Revises: b064519eb7d1
Create Date: 2026-04-04 18:26:30.275635
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '16d5f8ac96ff'
down_revision: str | None = 'b064519eb7d1'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_info_thread_bindings',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('thread_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('player_id'),
    sa.UniqueConstraint('thread_channel_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_info_thread_bindings')
    # ### end Alembic commands ###
