"""add match spectators

Revision ID: 23822cf317b8
Revises: 3273ba9b6be1
Create Date: 2026-03-21 14:24:18.478520
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '23822cf317b8'
down_revision: str | None = '3273ba9b6be1'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_spectators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'closed', name='match_spectator_status', native_enum=False, create_constraint=True), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removal_reason', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_match_spectators_match_id_status', 'match_spectators', ['match_id', 'status'], unique=False)
    op.create_index(op.f('ix_match_spectators_player_id'), 'match_spectators', ['player_id'], unique=False)
    op.create_index('uq_match_spectators_active_match_id_player_id', 'match_spectators', ['match_id', 'player_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_match_spectators_active_match_id_player_id', table_name='match_spectators', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_match_spectators_player_id'), table_name='match_spectators')
    op.drop_index('ix_match_spectators_match_id_status', table_name='match_spectators')
    op.drop_table('match_spectators')
    # ### end Alembic commands ###
