"""add outbox discarded_at

Revision ID: 244aeb05414b
Revises: c66a18962065
Create Date: 2026-03-24 01:41:29.996115
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '244aeb05414b'
down_revision: str | None = 'c66a18962065'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('discarded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_events', 'discarded_at')
    # ### end Alembic commands ###
