"""add match formats and player format stats

Revision ID: 3273ba9b6be1
Revises: 0360ead067b8
Create Date: 2026-03-21 13:05:22.478402
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '3273ba9b6be1'
down_revision: str | None = '0360ead067b8'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_format_stats',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('match_format', sa.Enum('1v1', '2v2', '3v3', name='match_format', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('rating', sa.Float(), server_default=sa.text('1500'), nullable=False),
    sa.Column('games_played', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('wins', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('losses', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('draws', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_played_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'match_format')
    )
    op.add_column('match_queue_entries', sa.Column('match_format', sa.Enum('1v1', '2v2', '3v3', name='match_format', native_enum=False, create_constraint=True), nullable=False))
    op.create_index(op.f('ix_match_queue_entries_match_format'), 'match_queue_entries', ['match_format'], unique=False)
    op.add_column('matches', sa.Column('match_format', sa.Enum('1v1', '2v2', '3v3', name='match_format', native_enum=False, create_constraint=True), nullable=False))
    op.add_column('matches', sa.Column('queue_class_id', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_matches_match_format'), 'matches', ['match_format'], unique=False)
    op.create_index(op.f('ix_matches_queue_class_id'), 'matches', ['queue_class_id'], unique=False)
    op.drop_column('players', 'rating')
    op.drop_column('players', 'draws')
    op.drop_column('players', 'games_played')
    op.drop_column('players', 'losses')
    op.drop_column('players', 'wins')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('wins', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('losses', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('games_played', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('draws', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('1500'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_matches_queue_class_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_match_format'), table_name='matches')
    op.drop_column('matches', 'queue_class_id')
    op.drop_column('matches', 'match_format')
    op.drop_index(op.f('ix_match_queue_entries_match_format'), table_name='match_queue_entries')
    op.drop_column('match_queue_entries', 'match_format')
    op.drop_table('player_format_stats')
    # ### end Alembic commands ###
