"""initial commit

Revision ID: 36e1433ee194
Revises: 
Create Date: 2026-03-31 00:05:51.282385
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '36e1433ee194'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managed_ui_channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ui_type', sa.Enum('register_panel', 'matchmaking_channel', 'matchmaking_news_channel', 'system_announcements_channel', 'admin_contact_channel', name='managed_ui_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_managed_ui_channels_ui_type'), 'managed_ui_channels', ['ui_type'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.Enum('presence_reminder', 'queue_expired', 'match_created', 'match_parent_assigned', 'match_report_opened', 'match_approval_requested', 'match_finalized', 'match_admin_review_required', name='outbox_event_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('failure_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_next_attempt_at'), 'outbox_events', ['next_attempt_at'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('display_name_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_discord_user_id'), 'players', ['discord_user_id'], unique=True)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('start_at < end_at', name='ck_seasons_start_before_end'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('end_at'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('start_at')
    )
    op.create_index(op.f('ix_seasons_name'), 'seasons', ['name'], unique=False)
    op.create_table('leaderboard_snapshots',
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('match_format', sa.Enum('1v1', '2v2', '3v3', name='match_format', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('snapshot_date', 'season_id', 'match_format', 'player_id')
    )
    op.create_table('match_queue_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('match_format', sa.Enum('1v1', '2v2', '3v3', name='match_format', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('queue_class_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'left', 'expired', 'matched', name='match_queue_entry_status', native_enum=False, create_constraint=True), server_default=sa.text("'waiting'"), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_present_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('last_reminded_revision', sa.Integer(), nullable=True),
    sa.Column('notification_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('presence_thread_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('notification_guild_id', sa.BigInteger(), nullable=True),
    sa.Column('notification_dm_discord_user_id', sa.BigInteger(), nullable=True),
    sa.Column('notification_interaction_application_id', sa.BigInteger(), nullable=True),
    sa.Column('notification_interaction_token', sa.Text(), nullable=True),
    sa.Column('notification_mention_discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('notification_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removal_reason', sa.Enum('user_leave', 'timeout', name='match_queue_removal_reason', native_enum=False, create_constraint=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_queue_entries_match_format'), 'match_queue_entries', ['match_format'], unique=False)
    op.create_index(op.f('ix_match_queue_entries_player_id'), 'match_queue_entries', ['player_id'], unique=False)
    op.create_index(op.f('ix_match_queue_entries_queue_class_id'), 'match_queue_entries', ['queue_class_id'], unique=False)
    op.create_index('uq_match_queue_entries_waiting_player_id', 'match_queue_entries', ['player_id'], unique=True, postgresql_where=sa.text("status = 'waiting'"))
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_format', sa.Enum('1v1', '2v2', '3v3', name='match_format', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('queue_class_id', sa.String(length=64), nullable=False),
    sa.Column('started_season_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['started_season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_match_format'), 'matches', ['match_format'], unique=False)
    op.create_index(op.f('ix_matches_queue_class_id'), 'matches', ['queue_class_id'], unique=False)
    op.create_index(op.f('ix_matches_started_season_id'), 'matches', ['started_season_id'], unique=False)
    op.create_table('player_access_restrictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('restriction_type', sa.Enum('queue_join', 'spectate', name='player_access_restriction_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_admin_discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('revoked_by_admin_discord_user_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_access_restrictions_player_id'), 'player_access_restrictions', ['player_id'], unique=False)
    op.create_index('ix_player_access_restrictions_player_type_created_at', 'player_access_restrictions', ['player_id', 'restriction_type', 'created_at'], unique=False)
    op.create_table('player_format_stats',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('match_format', sa.Enum('1v1', '2v2', '3v3', name='match_format', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('rating', sa.Float(), server_default=sa.text('1500'), nullable=False),
    sa.Column('games_played', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('wins', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('losses', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('draws', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_played_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('carryover_status', sa.Enum('pending', 'applied', 'not_applied', name='carryover_status', native_enum=False, create_constraint=True), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('carryover_source_season_id', sa.Integer(), nullable=True),
    sa.Column('carryover_source_rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['carryover_source_season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'season_id', 'match_format')
    )
    op.create_table('player_penalties',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('penalty_type', sa.Enum('incorrect_report', 'no_report', 'room_setup_delay', 'match_mistake', 'late', 'disconnect', name='penalty_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'penalty_type')
    )
    op.create_table('active_match_states',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('parent_deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parent_player_id', sa.Integer(), nullable=True),
    sa.Column('parent_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_open_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reporting_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provisional_result', sa.Enum('team_a_win', 'team_b_win', 'draw', 'void', name='active_match_state_provisional_result', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('admin_review_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('admin_review_reasons', sa.JSON(), nullable=False),
    sa.Column('state', sa.Enum('waiting_for_parent', 'waiting_for_result_reports', 'awaiting_result_approvals', 'finalized', name='match_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_by_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['parent_player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index(op.f('ix_active_match_states_parent_player_id'), 'active_match_states', ['parent_player_id'], unique=False)
    op.create_table('finalized_match_results',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('team_a_player_ids', sa.JSON(), nullable=False),
    sa.Column('team_b_player_ids', sa.JSON(), nullable=False),
    sa.Column('parent_player_id', sa.Integer(), nullable=True),
    sa.Column('parent_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provisional_result', sa.Enum('team_a_win', 'team_b_win', 'draw', 'void', name='finalized_match_provisional_result', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('final_result', sa.Enum('team_a_win', 'team_b_win', 'draw', 'void', name='finalized_match_final_result', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('admin_review_required', sa.Boolean(), nullable=False),
    sa.Column('admin_review_reasons', sa.JSON(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalized_by_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['parent_player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index(op.f('ix_finalized_match_results_parent_player_id'), 'finalized_match_results', ['parent_player_id'], unique=False)
    op.create_table('match_admin_overrides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('admin_discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('previous_final_result', sa.Enum('team_a_win', 'team_b_win', 'draw', 'void', name='match_admin_override_previous_result', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('new_final_result', sa.Enum('team_a_win', 'team_b_win', 'draw', 'void', name='match_admin_override_new_result', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_admin_overrides_match_id'), 'match_admin_overrides', ['match_id'], unique=False)
    op.create_table('match_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('queue_entry_id', sa.Integer(), nullable=False),
    sa.Column('team', sa.Enum('team_a', 'team_b', name='match_participant_team', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('notification_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('notification_guild_id', sa.BigInteger(), nullable=True),
    sa.Column('notification_mention_discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('notification_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['queue_entry_id'], ['match_queue_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id'),
    sa.UniqueConstraint('match_id', 'team', 'slot'),
    sa.UniqueConstraint('queue_entry_id')
    )
    op.create_index(op.f('ix_match_participants_match_id'), 'match_participants', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_participants_player_id'), 'match_participants', ['player_id'], unique=False)
    op.create_index(op.f('ix_match_participants_queue_entry_id'), 'match_participants', ['queue_entry_id'], unique=False)
    op.create_table('match_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('reported_input_result', sa.Enum('win', 'lose', 'draw', 'void', name='match_report_input_result', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('normalized_result', sa.Enum('team_a_win', 'team_b_win', 'draw', 'void', name='match_report_normalized_result', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_latest', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_reports_match_id'), 'match_reports', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_reports_player_id'), 'match_reports', ['player_id'], unique=False)
    op.create_index('uq_match_reports_latest_per_player', 'match_reports', ['match_id', 'player_id'], unique=True, postgresql_where=sa.text('is_latest'))
    op.create_table('match_spectators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'closed', name='match_spectator_status', native_enum=False, create_constraint=True), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removal_reason', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_match_spectators_match_id_status', 'match_spectators', ['match_id', 'status'], unique=False)
    op.create_index(op.f('ix_match_spectators_player_id'), 'match_spectators', ['player_id'], unique=False)
    op.create_index('uq_match_spectators_active_match_id_player_id', 'match_spectators', ['match_id', 'player_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('player_penalty_adjustments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('penalty_type', sa.Enum('incorrect_report', 'no_report', 'room_setup_delay', 'match_mistake', 'late', 'disconnect', name='penalty_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('auto_match_finalization', 'admin_manual', 'admin_result_override', name='penalty_adjustment_source', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('admin_discord_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_penalty_adjustments_match_id'), 'player_penalty_adjustments', ['match_id'], unique=False)
    op.create_index(op.f('ix_player_penalty_adjustments_penalty_type'), 'player_penalty_adjustments', ['penalty_type'], unique=False)
    op.create_index(op.f('ix_player_penalty_adjustments_player_id'), 'player_penalty_adjustments', ['player_id'], unique=False)
    op.create_table('active_match_player_states',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('report_status', sa.Enum('correct', 'incorrect', 'not_reported', name='match_report_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('approval_status', sa.Enum('not_required', 'pending', 'approved', 'not_approved', name='match_approval_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_report_id', sa.Integer(), nullable=True),
    sa.Column('last_reported_input_result', sa.Enum('win', 'lose', 'draw', 'void', name='match_report_input_result', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('last_normalized_result', sa.Enum('team_a_win', 'team_b_win', 'draw', 'void', name='active_match_player_last_normalized_result', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('last_reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['locked_report_id'], ['match_reports.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['active_match_states.match_id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('match_id', 'player_id')
    )
    op.create_index(op.f('ix_active_match_player_states_locked_report_id'), 'active_match_player_states', ['locked_report_id'], unique=False)
    op.create_table('finalized_match_player_results',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team', sa.Enum('team_a', 'team_b', name='match_participant_team', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('rating_before', sa.Float(), nullable=True),
    sa.Column('games_played_before', sa.Integer(), nullable=True),
    sa.Column('wins_before', sa.Integer(), nullable=True),
    sa.Column('losses_before', sa.Integer(), nullable=True),
    sa.Column('draws_before', sa.Integer(), nullable=True),
    sa.Column('latest_report_id', sa.Integer(), nullable=True),
    sa.Column('last_reported_input_result', sa.Enum('win', 'lose', 'draw', 'void', name='match_report_input_result', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('last_normalized_result', sa.Enum('team_a_win', 'team_b_win', 'draw', 'void', name='finalized_match_player_last_normalized_result', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('last_reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_status', sa.Enum('correct', 'incorrect', 'not_reported', name='match_report_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('approval_status', sa.Enum('not_required', 'pending', 'approved', 'not_approved', name='match_approval_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_penalty_type', sa.Enum('incorrect_report', 'no_report', 'room_setup_delay', 'match_mistake', 'late', 'disconnect', name='penalty_type', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('auto_penalty_applied', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['latest_report_id'], ['match_reports.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['finalized_match_results.match_id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('match_id', 'player_id')
    )
    op.create_index(op.f('ix_finalized_match_player_results_latest_report_id'), 'finalized_match_player_results', ['latest_report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finalized_match_player_results_latest_report_id'), table_name='finalized_match_player_results')
    op.drop_table('finalized_match_player_results')
    op.drop_index(op.f('ix_active_match_player_states_locked_report_id'), table_name='active_match_player_states')
    op.drop_table('active_match_player_states')
    op.drop_index(op.f('ix_player_penalty_adjustments_player_id'), table_name='player_penalty_adjustments')
    op.drop_index(op.f('ix_player_penalty_adjustments_penalty_type'), table_name='player_penalty_adjustments')
    op.drop_index(op.f('ix_player_penalty_adjustments_match_id'), table_name='player_penalty_adjustments')
    op.drop_table('player_penalty_adjustments')
    op.drop_index('uq_match_spectators_active_match_id_player_id', table_name='match_spectators', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_match_spectators_player_id'), table_name='match_spectators')
    op.drop_index('ix_match_spectators_match_id_status', table_name='match_spectators')
    op.drop_table('match_spectators')
    op.drop_index('uq_match_reports_latest_per_player', table_name='match_reports', postgresql_where=sa.text('is_latest'))
    op.drop_index(op.f('ix_match_reports_player_id'), table_name='match_reports')
    op.drop_index(op.f('ix_match_reports_match_id'), table_name='match_reports')
    op.drop_table('match_reports')
    op.drop_index(op.f('ix_match_participants_queue_entry_id'), table_name='match_participants')
    op.drop_index(op.f('ix_match_participants_player_id'), table_name='match_participants')
    op.drop_index(op.f('ix_match_participants_match_id'), table_name='match_participants')
    op.drop_table('match_participants')
    op.drop_index(op.f('ix_match_admin_overrides_match_id'), table_name='match_admin_overrides')
    op.drop_table('match_admin_overrides')
    op.drop_index(op.f('ix_finalized_match_results_parent_player_id'), table_name='finalized_match_results')
    op.drop_table('finalized_match_results')
    op.drop_index(op.f('ix_active_match_states_parent_player_id'), table_name='active_match_states')
    op.drop_table('active_match_states')
    op.drop_table('player_penalties')
    op.drop_table('player_format_stats')
    op.drop_index('ix_player_access_restrictions_player_type_created_at', table_name='player_access_restrictions')
    op.drop_index(op.f('ix_player_access_restrictions_player_id'), table_name='player_access_restrictions')
    op.drop_table('player_access_restrictions')
    op.drop_index(op.f('ix_matches_started_season_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_queue_class_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_match_format'), table_name='matches')
    op.drop_table('matches')
    op.drop_index('uq_match_queue_entries_waiting_player_id', table_name='match_queue_entries', postgresql_where=sa.text("status = 'waiting'"))
    op.drop_index(op.f('ix_match_queue_entries_queue_class_id'), table_name='match_queue_entries')
    op.drop_index(op.f('ix_match_queue_entries_player_id'), table_name='match_queue_entries')
    op.drop_index(op.f('ix_match_queue_entries_match_format'), table_name='match_queue_entries')
    op.drop_table('match_queue_entries')
    op.drop_table('leaderboard_snapshots')
    op.drop_index(op.f('ix_seasons_name'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_players_discord_user_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_outbox_events_next_attempt_at'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_managed_ui_channels_ui_type'), table_name='managed_ui_channels')
    op.drop_table('managed_ui_channels')
    # ### end Alembic commands ###
