"""add player access restrictions

Revision ID: 4941e9b35bcb
Revises: 23822cf317b8
Create Date: 2026-03-21 16:30:14.057986
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '4941e9b35bcb'
down_revision: str | None = '23822cf317b8'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_access_restrictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('restriction_type', sa.Enum('queue_join', 'spectate', name='player_access_restriction_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_admin_discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('revoked_by_admin_discord_user_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_access_restrictions_player_id'), 'player_access_restrictions', ['player_id'], unique=False)
    op.create_index('ix_player_access_restrictions_player_type_created_at', 'player_access_restrictions', ['player_id', 'restriction_type', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_player_access_restrictions_player_type_created_at', table_name='player_access_restrictions')
    op.drop_index(op.f('ix_player_access_restrictions_player_id'), table_name='player_access_restrictions')
    op.drop_table('player_access_restrictions')
    # ### end Alembic commands ###
