"""add rating tracking columns

Revision ID: 7015567383d7
Revises: f998fd25573c
Create Date: 2026-03-20 19:17:36.983065
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '7015567383d7'
down_revision: str | None = 'f998fd25573c'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finalized_match_player_results', sa.Column('rating_before', sa.Float(), nullable=True))
    op.add_column('finalized_match_player_results', sa.Column('games_played_before', sa.Integer(), nullable=True))
    op.add_column('finalized_match_player_results', sa.Column('wins_before', sa.Integer(), nullable=True))
    op.add_column('finalized_match_player_results', sa.Column('losses_before', sa.Integer(), nullable=True))
    op.add_column('finalized_match_player_results', sa.Column('draws_before', sa.Integer(), nullable=True))
    op.add_column('finalized_match_results', sa.Column('rated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('players', sa.Column('games_played', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('players', sa.Column('wins', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('players', sa.Column('losses', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('players', sa.Column('draws', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.alter_column('players', 'rating',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('1500'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'rating',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('1500'))
    op.drop_column('players', 'draws')
    op.drop_column('players', 'losses')
    op.drop_column('players', 'wins')
    op.drop_column('players', 'games_played')
    op.drop_column('finalized_match_results', 'rated_at')
    op.drop_column('finalized_match_player_results', 'draws_before')
    op.drop_column('finalized_match_player_results', 'losses_before')
    op.drop_column('finalized_match_player_results', 'wins_before')
    op.drop_column('finalized_match_player_results', 'games_played_before')
    op.drop_column('finalized_match_player_results', 'rating_before')
    # ### end Alembic commands ###
