"""update

Revision ID: 8b5f30ff8718
Revises: a8929a7cb0b0
Create Date: 2026-03-28 13:36:15.640551
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '8b5f30ff8718'
down_revision: str | None = 'a8929a7cb0b0'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
