"""make notification mention discord user id non-null

Revision ID: 9afb06a405d7
Revises: b0f7c1d3a9e2
Create Date: 2026-03-19 01:31:11.786953
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '9afb06a405d7'
down_revision: str | None = 'b0f7c1d3a9e2'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match_queue_entries', 'notification_mention_discord_user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match_queue_entries', 'notification_mention_discord_user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
