"""add queue joined outbox event

Revision ID: a5d3c328f06b
Revises: dd6414692355
Create Date: 2026-04-18 22:09:04.872079
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'a5d3c328f06b'
down_revision: str | None = 'dd6414692355'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
