"""update

Revision ID: a8929a7cb0b0
Revises: 0ed16e7622d7
Create Date: 2026-03-28 00:32:32.375881
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'a8929a7cb0b0'
down_revision: str | None = '0ed16e7622d7'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
