"""implement match flow management

Revision ID: b148b23ad678
Revises: b0f7c1d3a9e2
Create Date: 2026-03-18 01:20:26.591558
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'b148b23ad678'
down_revision: str | None = 'b0f7c1d3a9e2'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_penalties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('penalty_type', sa.Enum('incorrect_report', 'not_reported', 'room_delay', 'match_mistake', 'late', 'disconnect', name='player_penalty_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'penalty_type')
    )
    op.create_index(op.f('ix_player_penalties_player_id'), 'player_penalties', ['player_id'], unique=False)
    op.create_table('finalized_match_results',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('team_a_player_ids', sa.JSON(), nullable=False),
    sa.Column('team_b_player_ids', sa.JSON(), nullable=False),
    sa.Column('parent_player_id', sa.Integer(), nullable=True),
    sa.Column('parent_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_result', sa.Enum('team_a_win', 'team_b_win', 'draw', 'void', name='match_result_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['parent_player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index(op.f('ix_finalized_match_results_parent_player_id'), 'finalized_match_results', ['parent_player_id'], unique=False)
    op.create_table('match_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('reported_input_result', sa.Enum('win', 'loss', 'draw', 'void', name='match_report_input', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('normalized_result', sa.Enum('team_a_win', 'team_b_win', 'draw', 'void', name='match_result_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_latest', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_reports_match_id'), 'match_reports', ['match_id'], unique=False)
    op.create_index('ix_match_reports_match_player_latest', 'match_reports', ['match_id', 'player_id', 'is_latest'], unique=False)
    op.create_index(op.f('ix_match_reports_player_id'), 'match_reports', ['player_id'], unique=False)
    op.add_column('match_participants', sa.Column('report_status', sa.Enum('correct', 'incorrect', 'not_reported', name='match_participant_report_status', native_enum=False, create_constraint=True), nullable=True))
    op.add_column('match_participants', sa.Column('report_status_locked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('match_participants', sa.Column('approval_status', sa.Enum('not_required', 'pending', 'approved', 'not_approved', name='match_participant_approval_status', native_enum=False, create_constraint=True), nullable=True))
    op.add_column('match_participants', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('match_participants', sa.Column('auto_incorrect_penalty_applied', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('match_participants', sa.Column('auto_not_reported_penalty_applied', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('matches', sa.Column('state', sa.Enum('waiting_for_parent', 'waiting_for_result_reports', 'awaiting_result_approvals', 'finalized', name='match_state', native_enum=False, create_constraint=True), nullable=False))
    op.add_column('matches', sa.Column('parent_player_id', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('parent_decided_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('matches', sa.Column('report_open_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('matches', sa.Column('report_deadline_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('matches', sa.Column('approval_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('matches', sa.Column('approval_deadline_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('matches', sa.Column('provisional_result', sa.Enum('team_a_win', 'team_b_win', 'draw', 'void', name='match_result_type', native_enum=False, create_constraint=True), nullable=True))
    op.add_column('matches', sa.Column('admin_review_required', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_matches_parent_player_id'), 'matches', ['parent_player_id'], unique=False)
    op.create_foreign_key(None, 'matches', 'players', ['parent_player_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_index(op.f('ix_matches_parent_player_id'), table_name='matches')
    op.drop_column('matches', 'admin_review_required')
    op.drop_column('matches', 'provisional_result')
    op.drop_column('matches', 'approval_deadline_at')
    op.drop_column('matches', 'approval_started_at')
    op.drop_column('matches', 'report_deadline_at')
    op.drop_column('matches', 'report_open_at')
    op.drop_column('matches', 'parent_decided_at')
    op.drop_column('matches', 'parent_player_id')
    op.drop_column('matches', 'state')
    op.drop_column('match_participants', 'auto_not_reported_penalty_applied')
    op.drop_column('match_participants', 'auto_incorrect_penalty_applied')
    op.drop_column('match_participants', 'approved_at')
    op.drop_column('match_participants', 'approval_status')
    op.drop_column('match_participants', 'report_status_locked_at')
    op.drop_column('match_participants', 'report_status')
    op.drop_index(op.f('ix_match_reports_player_id'), table_name='match_reports')
    op.drop_index('ix_match_reports_match_player_latest', table_name='match_reports')
    op.drop_index(op.f('ix_match_reports_match_id'), table_name='match_reports')
    op.drop_table('match_reports')
    op.drop_index(op.f('ix_finalized_match_results_parent_player_id'), table_name='finalized_match_results')
    op.drop_table('finalized_match_results')
    op.drop_index(op.f('ix_player_penalties_player_id'), table_name='player_penalties')
    op.drop_table('player_penalties')
    # ### end Alembic commands ###
