"""add leaderboard snapshots

Revision ID: c5a187c7e86a
Revises: 288f167ce5a3
Create Date: 2026-03-22 22:35:24.373854
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'c5a187c7e86a'
down_revision: str | None = '288f167ce5a3'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard_snapshots',
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('match_format', sa.Enum('1v1', '2v2', '3v3', name='match_format', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('snapshot_date', 'season_id', 'match_format', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leaderboard_snapshots')
    # ### end Alembic commands ###
