"""add dm notification destination to match queue entries

Revision ID: c5a4116b4b6d
Revises: e407c45f3b94
Create Date: 2026-03-24 23:03:55.302085
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'c5a4116b4b6d'
down_revision: str | None = 'e407c45f3b94'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_queue_entries', sa.Column('notification_dm_discord_user_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_queue_entries', 'notification_dm_discord_user_id')
    # ### end Alembic commands ###
