"""add managed ui channels

Revision ID: c66a18962065
Revises: c5a187c7e86a
Create Date: 2026-03-24 01:17:31.221119
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'c66a18962065'
down_revision: str | None = 'c5a187c7e86a'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managed_ui_channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ui_type', sa.Enum('register_panel', name='managed_ui_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_managed_ui_channels_ui_type'), 'managed_ui_channels', ['ui_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_managed_ui_channels_ui_type'), table_name='managed_ui_channels')
    op.drop_table('managed_ui_channels')
    # ### end Alembic commands ###
