"""add player identity cache columns

Revision ID: ca1defc654ac
Revises: 4941e9b35bcb
Create Date: 2026-03-21 18:33:22.274625
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'ca1defc654ac'
down_revision: str | None = '4941e9b35bcb'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('players', sa.Column('display_name_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('players', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'last_seen_at')
    op.drop_column('players', 'display_name_updated_at')
    op.drop_column('players', 'display_name')
    # ### end Alembic commands ###
