"""track matchmaking panel message ids by format

Revision ID: d52a065afad7
Revises: 129c5d3ac194
Create Date: 2026-04-10 22:28:26.040078
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'd52a065afad7'
down_revision: str | None = '129c5d3ac194'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managed_ui_channels', sa.Column('matchmaking_one_v_one_message_id', sa.BigInteger(), nullable=True))
    op.add_column('managed_ui_channels', sa.Column('matchmaking_two_v_two_message_id', sa.BigInteger(), nullable=True))
    op.add_column('managed_ui_channels', sa.Column('matchmaking_three_v_three_message_id', sa.BigInteger(), nullable=True))
    op.alter_column('managed_ui_channels', 'message_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_unique_constraint(None, 'managed_ui_channels', ['matchmaking_one_v_one_message_id'])
    op.create_unique_constraint(None, 'managed_ui_channels', ['matchmaking_two_v_two_message_id'])
    op.create_unique_constraint(None, 'managed_ui_channels', ['matchmaking_three_v_three_message_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'managed_ui_channels', type_='unique')
    op.drop_constraint(None, 'managed_ui_channels', type_='unique')
    op.drop_constraint(None, 'managed_ui_channels', type_='unique')
    op.alter_column('managed_ui_channels', 'message_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('managed_ui_channels', 'matchmaking_three_v_three_message_id')
    op.drop_column('managed_ui_channels', 'matchmaking_two_v_two_message_id')
    op.drop_column('managed_ui_channels', 'matchmaking_one_v_one_message_id')
    # ### end Alembic commands ###
