"""add interaction notification context to match queue entries

Revision ID: e407c45f3b94
Revises: 244aeb05414b
Create Date: 2026-03-24 21:14:45.794536
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'e407c45f3b94'
down_revision: str | None = '244aeb05414b'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_queue_entries', sa.Column('notification_interaction_application_id', sa.BigInteger(), nullable=True))
    op.add_column('match_queue_entries', sa.Column('notification_interaction_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_queue_entries', 'notification_interaction_token')
    op.drop_column('match_queue_entries', 'notification_interaction_application_id')
    # ### end Alembic commands ###
